// Generator: src/client/index.jsx → lib/client.js (bundle artifact shipped
// with the plugin).
//
// The optional asset assets/background.mp4 is base64-embedded into the
// bundle as a data URL (via the generated src/client/media.gen.js), so the
// plugin keeps playing after the source video file is deleted — the plugin
// IS the video. The embedded media behaves like any user-added file in the
// plugin's media list (deletable; a persisted flag hides it forever).
// Without the asset there is no bundled media at all and the background
// simply stays off until the user adds a file.
//
// The output wraps the esbuild CJS output in the official
// __ModuleLoader__.load contract; 'react' and the shell seeds
// (@deepseek-ai/dsh-client-ui-primitives) stay external.
import { buildSync } from 'esbuild';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ASSET = resolve(ROOT, 'assets', 'background.mp4');
const GEN = resolve(ROOT, 'src', 'client', 'media.gen.js');
const OUTPUT = resolve(ROOT, 'lib', 'client.js');
const PLUGIN_ID = 'dsh-video-background';
const MIME = 'video/mp4';
/**
 * Display name of the bundled media shown in the plugin's media list.
 * Change this when you swap assets/background.mp4 for another file.
 */
const MEDIA_NAME = '多娜多娜 × Muse Dash.mp4';
/** Warn (not fail) above this embed size; the bundle grows ~1.33x. */
const MAX_BYTES = 3 * 1024 * 1024;

function mediaSource() {
  if (!existsSync(ASSET)) {
    return '// generated by build-client.mjs\n'
      + '// no assets/background.mp4 — no bundled media\n'
      + 'export const HAS_VIDEO = false;\n'
      + 'export const MEDIA_URL = null;\n'
      + 'export const MEDIA_NAME = null;\n'
      + 'export const MEDIA_SIZE = 0;\n';
  }
  const bytes = readFileSync(ASSET);
  if (bytes.length > MAX_BYTES) {
    console.warn(`[build-client] WARNING: asset is ${(bytes.length / 1024 / 1024).toFixed(1)} MB — base64 embedding inflates the bundle ~1.33x; consider a shorter/lower-bitrate loop.`);
  }
  return '// generated by build-client.mjs (embedded asset)\n'
    + 'export const HAS_VIDEO = true;\n'
    + `export const MEDIA_URL = ${JSON.stringify(`data:${MIME};base64,${bytes.toString('base64')}`)};\n`
    + `export const MEDIA_NAME = ${JSON.stringify(MEDIA_NAME)};\n`
    + `export const MEDIA_SIZE = ${bytes.length};\n`;
}

export function generate({ check = false } = {}) {
  const mediaSrc = mediaSource();
  if (!existsSync(GEN) || readFileSync(GEN, 'utf8') !== mediaSrc) {
    writeFileSync(GEN, mediaSrc);
  }

  const result = buildSync({
    entryPoints: [resolve(ROOT, 'src', 'client', 'index.jsx')],
    bundle: true,
    format: 'cjs',
    platform: 'browser',
    target: 'es2020',
    external: ['react', '@deepseek-ai/dsh-client-ui-primitives'],
    jsx: 'transform',
    jsxFactory: 'React.createElement',
    jsxFragment: 'React.Fragment',
    write: false,
    logLevel: 'silent',
  });
  const body = result.outputFiles[0].text.replace(/\n$/, '');
  const code = 'window.__ModuleLoader__.load({\n'
    + '\tid: ' + JSON.stringify(PLUGIN_ID) + ',\n'
    + '\tfactory: (require) => {\n'
    + '\t\tvar module = { exports: {} };\n'
    + '\t\tvar exports = module.exports;\n'
    + body
    + '\n\t\treturn module.exports;\n'
    + '\t}\n'
    + '});\n';
  if (check) {
    const committed = readFileSync(OUTPUT, 'utf8');
    if (committed !== code) {
      console.error('[build-client] lib/client.js is stale — run: node scripts/build-client.mjs');
      process.exit(1);
    }
    console.log('[build-client] lib/client.js is fresh (--check OK)');
    return;
  }
  writeFileSync(OUTPUT, code);
  const mode = mediaSrc.includes('HAS_VIDEO = true') ? 'video embedded' : 'no bundled media';
  console.log(`[build-client] lib/client.js generated (${code.length} bytes) [${mode}]`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  generate({ check: process.argv.includes('--check') });
}
